@startuml ホテル予約
class 利用者{
    -名前
    -住所
    -電話番号
}
class ホテル{
    -部屋
}
class 部屋{
    -タイプ
    -価格
    -キャンペーン価格
}
class 予約{
    -チェックイン日
    -滞在期間
    -値段
}

ホテル "0..*" o-up-- "1" 部屋
ホテル o-- 利用者:会員 >
利用者 --> 予約



@enduml