@startuml ホテル
object "<u>Aさん:お客様</u>" as c1{
名前
宿泊日:5月3日
宿泊日数=2
}
object "<u>Bさん:お客様</u>" as c2{
名前
宿泊日:5月3日
宿泊日数=2
}
object "<u>ホテルUML:ホテル</u>" as hotel{
    キャンペーン期間:4月29日から5月6日まで
}
object "<u>301号室:客室</u>" as room1{
料金(円)=11000
キャンペーン価格(円)=9000
}
object "<u>302号室:客室</u>" as room2{
料金(円)=11000
キャンペーン価格(円)=9000
}
object "<u>303号室:客室</u>" as room3{
料金(円)=11000
キャンペーン価格(円)=9000
}

c1 "1" -- "1" room1: 宿泊
c2 "1" -- "1" room3: 宿泊
room1 "*" -- "1" hotel: 部屋 <
room2 "*" -- "1" hotel: 部屋 <
room3 "*" -- "1" hotel: 部屋 <
@enduml