@startuml ステートマシン 
top to bottom direction
[*] -> メニュー :接続
メニュー -> [*] :完了
予約と確認 ---> メニュー :　キャンセル
メニュー ---> 予約と確認 :予約
予約と確認 -right-> あなたの順番 : 登録
あなたの順番 -right-> 予約と確認 :　キャンセル
あなたの順番 --> メニュー : 取消し
今の順番 -> メニュー : 順番の表示
メニュー -> 今の順番 : 順番の確認
@enduml